### ISSUE TITLE
macos sierra cpu 100%

### ISSUE THREAD

**Issue by warmonipa** [kaiye/kaiye.github.com#22]
Recently alfred cpu usage 100% frequently,plz check

<img width="1335" alt="alfred" src="https://cloud.githubusercontent.com/assets/1324712/26477814/d31e8c34-41fa-11e7-8e34-4eba7b875a0d.png">

**Comment by kaiye** [comment]
刚本地检查了下是正常的，`top` 中也没有 alfred cpu 100%

```
➜  Markdown git:(master) ✗ ps -ef | grep -i alfred
  501 24810     1   0 15May17 ??         9:39.22 /Applications/Alfred 3.app/Contents/MacOS/Alfred 3
  501 24816     1   0 15May17 ??         0:37.61 /Applications/Alfred 3.app/Contents/Services/Alfred Text Service.app/Contents/MacOS/Alfred Text Service -psn_0_942310
  501 34776 94953   0 11:24AM ttys002    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn -i alfred
```

从你的截图上看估计是 background 进程卡死了。这里用了一个开源的框架，会自动检查插件有没有更新，如果你的本地网络访问 github 不稳定的话也许会卡住。由于 [kaiye/workflows-youdao](https://github.com/kaiye/workflows-youdao)  项目已经一年没更新了，建议你可以手动 kill 掉这个进程，或者删掉 workflows 重新安装下。

另外这个项目的 issues 是我用来写 blog 的，插件问题可以在插件项目去开 issues ，或者在我对应的「#5 学英语和写工具」下评论，thx

**Comment by warmonipa** [comment]
抱歉，这个问题一直在复现，我解决的方法就是杀python进程  ，我先把这个issue关了吧
